### ISSUE TITLE
Element seems to center the marker on info panel show and might end up going off screen

### ISSUE THREAD

**Issue by lbustelo** [mlisook/paper-map-info#6] opened 2016-06-21 18:53 UTC
See this screenshot. 

![info_panel_working](https://cloud.githubusercontent.com/assets/2474841/16242267/4b03b20a-37b7-11e6-87b5-92371f983117.gif)

When using the built-in info panel, it figures out when it need to pan the map so both the marker and the info panel is visible.

See this screenshot to show how this works with the existing code in `google-map`.

![info_panel_old_code](https://cloud.githubusercontent.com/assets/2474841/16242324/940e1ec2-37b7-11e6-880f-bbf57c0b03e2.gif)

**Comment by lbustelo** [comment] 2016-06-21 18:57
Ha! Notice that I'm driving selection from that side panel... when I select by clicking on the marker on the map directly, then it works.

**Comment by mlisook** [comment] 2016-06-21 19:49
First off, your app looks nice.

I don't see how it would make a difference if the selection comes from clicking a marker or some other event.

The control pans the map only if, based on it's size, it would  extend over the top, left or right edges of the map.  Then it pans down, right or left so that overlapping edge is 10px inside.

It's a little difficult for me to understand why the effect in the picture is happening.  First, it almost looks like the where should I eat toolbar is on top of the map, is it?  Second, when you are clicking on the sidebar, the marker for that location is not on the screen at all.  Are you adding the marker after the click? (That should be fine, just trying to understand what might be happening).  

Perhaps the only other thought I have right now, without seeing the code is that the paper-map-info tag could be outside the google-map tag.

**Comment by lbustelo** [comment] 2016-06-21 20:13
> First, it almost looks like the where should I eat toolbar is on top of the map, is it?

No... there is no overlap... the bounds of the map is what you see.

> Second, when you are clicking on the sidebar, the marker for that location is not on the screen at all. Are you adding the marker after the click? 

It is the same marker... just changing it's lat/long as I select. But I'm calling code to make the map show the marker....

```
listTemplate.handleItemClick = function(e){
            if(!selMarker.open){
                selMarker.async(function(){
                    theMap.map.panTo(selMarker.marker.getPosition());
                }, 500);
            }
        }
```

I think the problem is that when I make the call to `panTo` and the `google-map` is using its internal infoPanel, it take that into account to move the marker in the correct place. I guess that with your element, the map is not aware of the dialog bounds, so it ends up panning the marker to the center.

At some point, I'll open source the app and you can take a closer look... for now, here is a snippet.

``` html
<google-map id="theMap" latitude="{{center_lat}}" longitude="{{center_long}}" 
        zoom="15" disable-zoom disable-default-ui single-info-window
        drag-events on-google-map-dragend="handleMapDragged"
        on-google-map-ready="handleMapReady">

        <template is="dom-repeat" items="[[near.data]]">
            <google-map-marker latitude="[[item.6]]" longitude="[[item.7]]" 
                title="[[item.1]]" data-restid$="[[item.0]]"
                icon="images/[[item.8]]_score.png"
                click-events on-google-map-marker-click="handleMarkerClick"></google-map-marker>
        </template>

        <template is="dom-if" if="[[sel_rest]]">
            <google-map-marker id="selMarker" latitude="[[sel_rest.latitude]]" longitude="[[sel_rest.longitude]]" 
                title="[[sel_rest.restaurant_name]]" data-restid$="[[item.facility_id]]"
                click-events on-google-map-marker-click="handleMarkerOpen"></google-map-marker>
            <paper-map-info id="myinfocard" fade-in>
                <div class="rest-details">
                    <paper-item data-restid$="[[sel_rest.facility_id]]" class$="score-[[sel_rest.letter_score]]">
                        <paper-item-body three-line>
                            <div>[[sel_rest.restaurant_name]]</div>
                            <div secondary class="blue">Score: [[sel_rest.score]] <paper-progress value="[[sel_rest.score]]" style="display: inline-block;margin-bottom: 3px;"></paper-progress></div>
                            <div secondary>Last inspection: [[sel_rest.inspection_date]]</div>
                            <div secondary>[[sel_rest.address]]</div>
                        </paper-item-body>
                    </paper-item>
                    <urth-viz-line id="viz" width="500" height="300" datarows='{{scores.data}}' columns='{{scores.columns}}' ybounds="[60,100]">
                        <urth-viz-col index="0" type="date" format="%b %d %Y"></urth-viz-col>
                    </urth-viz-line>
                </div>
            </paper-map-info>
        </template>
    </google-map>
```

**Comment by mlisook** [comment] 2016-06-21 21:34
I think the problem is that `listTemplate.handleItemClick` pans the map after the paper-map-info is already open - `selMarker.async(function(){ ... }, 500)`.  This is equivalent to the user panning the map and I don't have the paper-map-info fighting with the user over the position by trying to reposition their intentional position.  If you do `this.$.myinfocard.showInfoWindow(selMarker.marker)` after panning to your spot, then the paper-map-info will reposition the window if necessary to fit.

I'm attaching a very simplified project showing what I'm saying (you'll have to do a bower install to run it).  In this I made the contents large enough, and the map small enough, that the PIM would need an automatic pan.

[pmi-issue6.zip](https://github.com/mlisook/paper-map-info/files/326638/pmi-issue6.zip)

**Comment by mlisook** [comment] 2016-06-21 22:23
I just noticed in my sample I have `this.$.pmi.close()`, but that isn't really necessary, just the call to `this.$.pmi.showInfoWindow(this.marker)` after `this.$.theMap.map.panTo(this.marker.getPosition())`.

**Comment by lbustelo** [comment] 2016-06-22 16:27
So I have not gotten a chance to test your sample, but I did remove the code to `pan` the marker on selection and it did get better. 

See below

![selection_moves_sortof](https://cloud.githubusercontent.com/assets/2474841/16274675/3b46e002-386c-11e6-8e96-8ca11d7b0029.gif)

It seems that if the marker is completely outside the viewport, it is not getting panned into view. When the parker is already in view, then it seems to get correctly panned so that both the marker and the info panel fits.

**Comment by mlisook** [comment] 2016-06-22 20:05
Yes, I notice when you click the McDonalds, for example, the pin is off screen.  Maybe it would be better to have the `panTo` in as you had it, but add the  `showInfoWindow` right after that inside the `selMarker.async(function(){ ...` which would ensure the marker is on the map as you intended originally.

Nevertheless, _I do think it's a bug in pmi_ when the pin is below the visible area of the map and it doesn't pan up into view.  I need to look into it.

**Comment by mlisook** [comment] 2016-07-05 13:09
I'm closing this based on the update and discussion.

**Closed as completed by mlisook** 2016-07-05 13:09 UTC
